blog/urls.py
from django.conf.urls import patterns,url,include
from django.conf import settings
from django.conf.urls.static import static
from blog import views

urlpatterns = patterns('',
	url(r'^$',views.index,name='index'),
	url(r'^list/$',views.list,name='list'),
	url(r'^edit/$',views.edit,name='edit'),
	url(r'^blog/(?P<pk>\d+)/$',views.detail,name='detail'),
	url(r'^blog/(?P<pk>\d+)/update/$',views.update,name='update'),
	url(r'^blog/(?P<pk>\d+)/remvoe/$',views.remove,name='remove'),
	url(r'^aboutme/$',views.aboutme,name='aboutme'),
	url(r'^search/',views.search,name='search'),
)+static(settings.MEDIA_URL,document_root=settings.MEDIA_ROOT)

myproject/urls.py
from django.conf.urls import patterns, include, url
from django.conf import settings
from django.conf.urls.static import static
from django.contrib import admin

urlpatterns = patterns('',
	url(r'',include('blog.urls',namespace='blog')),
	url(r'^admin/', include(admin.site.urls)),
	url(r'^accounts/login/$','django.contrib.auth.views.login'),
	url(r'^accounts/logout/$','django.contrib.auth.views.logout',{'next_page':'/'}),
	url(r'^ckeditor/',include('ckeditor.urls'))
)+static(settings.MEDIA_URL,document_root=settings.MEDIA_ROOT)

blog/models.py
#coding:utf-8
from django.db import models
from django.contrib.auth.models import User
from django.utils import timezone
from django import forms
from ckeditor.fields import RichTextField
from ckeditor.widgets import CKEditorWidget
from django.forms import ModelForm
# Create your models here.
class Blog(models.Model):
	class Meta:
		verbose_name=u'文章'
		verbose_name_plural=u'文章'
	user=models.ForeignKey(User,verbose_name=u'作者')
	title=models.CharField(max_length=200,verbose_name=u'文章标题')
	text=RichTextField(verbose_name=u'正文内容')
	created_time=models.DateTimeField(default=timezone.now,verbose_name=u'创建时间')
	published_time=models.DateTimeField(blank=True,null=True,verbose_name=u'发布时间')
	visitors=models.IntegerField(default=0,verbose_name=u'访问量')

	def __unicode__(self):
		return self.title

class PostForm(ModelForm):
	class Meta:
		model=Blog
		fields=('title','text',)

blog/views.py
#coding:utf-8
import sys
reload(sys)
sys.setdefaultencoding('utf8')

from django.shortcuts import render,get_object_or_404,redirect
from django.core.urlresolvers import reverse
from django.http import HttpResponseRedirect
from blog.models import Blog,PostForm
from django.core.paginator import Paginator,EmptyPage,PageNotAnInteger
from django.contrib.auth.decorators import login_required
from haystack.forms import SearchForm
import datetime

def index(request):

	mblogs=Blog.objects.all().order_by('-visitors')[:5]
	blog_list=Blog.objects.all().order_by('-published_time')
	paginator=Paginator(blog_list,3)
	
	page=request.GET.get('page')

	try:
		blogs=paginator.page(page)
	except PageNotAnInteger:
		blogs=paginator.page(1)
	except EmptyPage:
		blogs=paginator.page(paginator.num_pages)

	return render(request,'blog/index.html',{'blogs':blogs,'mblogs':mblogs})
	
def list(request):
	blog_list=Blog.objects.all().order_by('-published_time')
	mblogs=Blog.objects.all().order_by('-visitors')[:5]
        paginator=Paginator(blog_list,10)

        page=request.GET.get('page')

        try:
                blogs=paginator.page(page)
        except PageNotAnInteger:
                blogs=paginator.page(1)
        except EmptyPage:
                blogs=paginator.page(paginator.num_pages)

        return render(request,'blog/blog_list.html',{'blogs':blogs,'mblogs':mblogs})

def detail(request,pk):
	post=get_object_or_404(Blog,pk=pk)
	mblogs=Blog.objects.all().order_by('-visitors')[:5]
	post.visitors=post.visitors+1
	post.save()
	return render(request,'blog/detail.html',{'blog':post,'mblogs':mblogs})	

@login_required
def edit(request):
	mblogs=Blog.objects.all().order_by('-visitors')[:5]
	if request.method=='POST':
		form=PostForm(request.POST)
		if form.is_valid():
			post=form.save(commit=False)
			post.user=request.user
			post.created_time=datetime.datetime.now()
			post.published_time=datetime.datetime.now()
			post.save()
			return render(request,'blog/detail.html',{'blog':post,'mblogs':mblogs})
	else:
		form=PostForm()
	return render(request,'blog/edit.html',{'form':form,'mblogs':mblogs})

@login_required
def update(request,pk):
	mblogs=Blog.objects.all().order_by('-visitors')[:5]
	post=get_object_or_404(Blog,pk=pk)
	if request.method=="POST":
                form=PostForm(request.POST,instance=post)
		if form.is_valid():
			post=form.save(commit=False)
			post.user=request.user
			post.save()
			return render(request,'blog/detail.html',{'blog':post,'mblogs':mblogs})
	else:
		form=PostForm(instance=post)
        return render(request,'blog/update.html',{'form':form,'mblogs':mblogs})

@login_required
def remove(request,pk):
	mblogs=Blog.objects.all().order_by('-visitors')[:5]
	blog=get_object_or_404(Blog,pk=pk)
	Blog.objects.filter(pk=pk).delete()
        return render(request,'blog/after_remove.html',{'mblogs':mblogs})

def aboutme(request):	
	mblogs=Blog.objects.all().order_by('-visitors')[:5]
	return render(request,'blog/aboutme.html',{'mblogs':mblogs})

def search(request):
	mblogs=Blog.objects.all().order_by('-visitors')[:5]
	keywords=request.GET['q']
	keywords.encode('gb2312')
	sform=SearchForm(request.GET)
	blogs=sform.search()
	return render(request,'blog/search.html',{'mblogs':mblogs,'blogs':blogs,'list_header':'关键字\'{}\'搜索结果'.format(keywords)})
	

blog/templates/blog/aboutme.html
{% extends 'blog/base.html' %}
{% block content %}
<p>以后再补充</p>
{% endblock %}

blog/templates/blog/after_remove.html
{% extends 'blog/base.html' %}
{% block content %}
<a href={% url 'blog:index' %}>返回主页</a>
<a href={% url 'blog:list' %}>返回博客列表页面</a>
{% endblock %}

blog/templates/blog/base.html
{% load staticfiles %}
<!DOCTYPE html>
<html xmlns="http://www.w3.org/1999/xhtml">
<head>
	<title>能近取譬</title>
	<meta http-equiv="Content-Type" content="text/html" charset="gb2312" />
	<link href="{% static 'blog/style.css' %}" rel="stylesheet" type="text/css" />
	<link rel="stylesheet" href="//maxcdn.bootstrapcdn.com/bootstrap/3.2.0/css/bootstrap.min.css">
	<link rel="stylesheet" href="//maxcdn.bootstrapcdn.com/bootstrap/3.2.0/css/bootstrap-theme.min.css">
	<script src="//maxcdn.bootstrapcdn.com/bootstrap/3.2.0/js/bootstrap.min.js"></script>
	<script type="text/javascript" src="/static/ckeditor/ckeditor/ckeditor.js"></script>
	<!-- CuFon ends -->
</head>
<body>
	<div class="container">
		<div class="row">
			<div class="col-md-8"><h1><a href="/">能近取譬</a></h1></div>
			<div class='col-md-4'>
			{% if user.is_authenticated %}
			<p>欢迎您，{{user.username}}!<a href="{% url 'django.contrib.auth.views.logout' %}">登出</a></p>
			{% else %}
			<p>欢迎您，游客!<a href="{% url 'django.contrib.auth.views.login' %}">登录</a></p>
			{% endif %}
			</div>
		</div>
		<div class="row">
			<div class="col-md-6">
				<div class="nav" role="navigation">
					<ul class='nav nav-tabs'>
          					<li role='prensentation' class="active"><a href="{% url 'blog:index' %}">主页</a></li>
          					<li role="prensentation"><a href="{% url 'blog:list' %}">博客</a></li>
          					<li role="presentation" ><a href="http://shop102757287.taobao.com/?spm=a230r.7195193.1997079397.2.whO1jy">老婆的淘宝店</a></li>
          					<li role="presentation" ><a href="{% url 'blog:aboutme' %}">关于我</a></li>
					</ul>
      				</div>
    			</div>
  		</div>
	</div>



	<div class="container">
		<div class="row">
    			<div class="col">
      				<div class="col-md-8">
				{% block content %}
				{% endblock %}
				</div>
				<div class="col-md-4">
					<div id="searchbox">
						<form action="{% url 'blog:search' %}" method="get">
        						<div class="content">
            							<label>
                							<input type="text" class="textfield searchtip" name="q" size="20" value="">
            							</label>
            							<input type="submit" class="button" value="搜索">
       		 					</div>
    						</form>
					</div>
          				<h4><span>最热博文排行榜</span></h4>
            				{% for blog in mblogs %}
					<p><a href={% url 'blog:detail' blog.pk %}>{{blog.title}}({{blog.visitors}})</a></p>
					{% endfor %}
          				<h4><span>友情链接</span></h4>
            				<a href="http://www.baidu.com" >百度</a>
      				</div>
    			</div>
		</div>
		<div class="row">
			<div class="col-md-12">
      				<p class="lf">&copy; Copyright <a href="/">能近取譬</a></p>
			</div>
		</div>
	</div>
</body>
</html>

blog/templates/blog/blog_list.html
{% extends 'blog/base.html' %}
{% block content %}
<div class='col-md-2 col-md-offset-10'>
	<a href={% url 'blog:edit' %}><span class="glyphicon glyphicon-plus" aria-hidden="true"></span></a>
</div>
{% if blogs %}
<ul>
{% for blog in blogs %}
	<li><h5><a href='{% url 'blog:detail' blog.pk %}'>{{blog.title}}</a></h5></li>
{% endfor %}
</ul>
{% else %}
<p>博主太懒了，还没有写博客。</p>
{% endif %}
{% endblock %}

blog/templates/blog/detail.html
{% extends 'blog/base.html' %}
{% block content %}
	<div class="col-md-4 col-md-offset-10">
		{% if user.is_authenticated %}
		<a href={% url 'blog:update' pk=blog.pk %}><span class="glyphicon glyphicon-pencil" aria-hidden="true"></span></a>
		<a href={% url 'blog:remove' pk=blog.pk %}><span class="glyphicon glyphicon-remove" aria-hidden="true"></span></a>
		{% else %}
		<a href="{% url 'django.contrib.auth.views.login' %}" class="top-menu"><span class="glyphicon glyphicon-lock"></span></a>
		{% endif %}
	</div>
	<div class="blog-post">
		<h3 class="blog-post-title"><a href='#'>{{blog.title|truncatechars:20}}</a></h3>
		<p>Published {{blog.published_time}}</p>
		<p class="blog-post-meta">{{blog.text|safe|linebreaks}}</p>
	</div>
{% endblock content %}

blog/templates/blog/edit.html
{% extends 'blog/base.html' %}
{% block content %}
		<form  method="post">
			{% csrf_token %}
			<div class='form-group'>
				<label for="id_title" class="col-sm-2 control-label">标题</label>
				<div class="col-sm-10">
					<input type="text" class="form-control" id="id_title" name='title' placeholder="输入博客标题">
				</div>
			</div>
			<div class="form-group">
				<label for="id_text" class="col-sm-2 control-label">正文</label>
				<div class="col-sm-10">
                               		<textarea  rows=20 class="ckeditor" id="id_text"  name='text' placeholder="输入博客内容"></textarea>
				</div>
			</div>
			<div class="form-group">
				<div class="col-sm-offset-2 col-sm-10">	
					<button type="submit">保存</button>
				</div>
			</div>
		</form>
{% endblock %}

blog/templates/blog/index.html
{% extends 'blog/base.html' %}
{% block content %}
<div class="article">
	{% if blogs %}
	{% for blog in blogs %}
	<a href="{% url 'blog:detail' blog.id %}"><h3>{{blog.title|truncatechars:30}}</h3></a>
	<p><span class='date'>发布日期:{{blog.published_time}}</span>&nbsp;|&nbsp;作者:{{blog.user}}&nbsp;|&nbsp;访问量:{{blog.visitors}}<p>
	{{blog.text|safe|linebreaks|truncatechars:200}}
	<p class="lead"><a href="{% url 'blog:detail' blog.id %}">阅读更多</a></p>
	{% endfor %}
	{% else %}
	<p>No blogs published</p>
	{% endif %}
</div>
<div class="pagination">
	<span class="step-links">
	{% if blogs.has_previous %}
	<a href="?page={{ blogs.previous_page_number }}">previous</a>
	{% endif %}
		<span class="current">
			Page {{ blogs.number }} of {{ blogs.paginator.num_pages }}.
		</span>
	{% if blogs.has_next %}
	<a href="?page={{ blogs.next_page_number }}">next</a>
	{% endif %}		
	</span>
</div>
{% endblock content %}

blog/templates/blog/index_back.html
{% extends 'blog/base.html' %}
{% block content %}
<div class="article">
	{% if blogs %}
	{% for blog in blogs %}
	<a href="{% url 'blog:detail' blog.id %}"><h3>{{blog.title|truncatechars:30}}</h3></a>
	<p><span class='date'>发布日期:{{blog.published_time}}</span>&nbsp;|&nbsp;作者:{{blog.user}}&nbsp;|&nbsp;访问量:{{blog.visitors}}<p>
	{{blog.text|linebreaks|truncatechars:200}}
	<p class="lead"><a href="{% url 'blog:detail' blog.id %}">readmore</a></p>
	{% endfor %}
	{% else %}
	<p>No blogs published</p>
	{% endif %}
</div>
<div class="pagination">
	<span class="step-links">
	{% if blogs.has_previous %}
	<a href="?page={{ blogs.previous_page_number }}">previous</a>
	{% endif %}
		<span class="current">
			Page {{ blogs.number }} of {{ blogs.paginator.num_pages }}.
		</span>
	{% if blogs.has_next %}
	<a href="?page={{ blogs.next_page_number }}">next</a>
	{% endif %}		
	</span>
</div>
{% endblock content %}

blog/templates/blog/search.html
{% extends 'blog/base.html' %}
{% block content %}
        {% if query %}
            <h3>Results</h3>

            {% for blog in blogs %}
                <p>
                    <a href="{{ blog.get_absolute_url }}">{{ blog.title }}</a>
                </p>
            {% empty %}
                <p>No results found.</p>
            {% endfor %}

            {% if page.has_previous or page.has_next %}
                <div>
                    {% if page.has_previous %}<a href="?q={{ query }}&amp;page={{ page.previous_page_number }}">{% endif %}&laquo; Previous{% if page.has_previous %}</a>{% endif %}
                    |
                    {% if page.has_next %}<a href="?q={{ query }}&amp;page={{ page.next_page_number }}">{% endif %}Next &raquo;{% if page.has_next %}</a>{% endif %}
                </div>
            {% endif %}
        {% else %}
            {# Show some example queries to run, maybe query syntax, something else? #}
        {% endif %}
  



{% if blogs %}
	{% for blog in blogs %}
		<a href="{% url 'blog:detail' pk=blog.pk %}" ><h4>{{blog.title}}</h4></a>
		<p>{{blog.text|linebreaks|truncatechars:90}}</p>
	{% endfor %}
{% else %}
	<p>No searched</p>
{% endif %}
{% endblock %}

blog/templates/blog/update.html
{% extends 'blog/base.html' %}
{% block content %}
		<form  method="post">
			{% csrf_token %}
			<div class='form-group'>
				<label for="id_title" class="col-sm-2 control-label">标题</label>
				<div class="col-sm-10">
					<!--input type="text" class="form-control" id="id_title" name='title' placeholder="输入博客标题"-->
					{{form.title}}
				</div>
			</div>
			<div class="form-group">
				<label for="id_text" class="col-sm-2 control-label">正文</label>
					<div class='col-sm-10'>
                               		<textarea class='ckeditor' rows=20  id="id_text" name='text' value={{form.text|safe}}
			</div>
			<div class="form-group">
				<div class="col-sm-offset-2 col-sm-10">	
					<button type="submit">保存</button>
				</div>
			</div>
		</form>
{% endblock %}